services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Keins123!
      MYSQL_DATABASE: BarbotDB
      MYSQL_USER: vscode
      MYSQL_PASSWORD: Keins123!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  flask:
    build: .
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  db_data:
